- DB/CANDB.dbc
- tc275_project/inc/OurCan.h
- tc275_project/inc/OurCan_message.h
- tc275_project/inc/OurCan_signal.h
- tc275_project/src/OurCan.c
- tc275_project/src/example_main.c
> [PR] CAN 통신 노검증본

- DB/CANDB.dbc
- tc275_project/inc/OurCan_signal.h
> [PR] DB 및 signal 수정, Audio_file 4->6 bit

- DB/CANDB.dbc
> [PR] DB파일변경

- tc275_project/Cpu0_Main.c
> [PR] bug fix Cpu0_Main.c

- tc275_project/Cpu0_Main.c
> [PR] TC275 Cpu0_Main.c bug fix

- tc275_project/Cpu0_Main.c
[Cpu0_Main.c]
스마트 제어 off 시에도 안전 동작이 수행되도록 변경
주석 추가,
각 동작에 대한 초기화 대기 시간 수정
> [PR] 차량 내부 TC275 로직 수정본 업로드

- stm32_project/Core/Inc/hvac.h
- stm32_project/Core/Src/hvac.c
> [PR] 공조시스템 추가 (hvac)

- stm32_project/Core/Src/main.c
> [PR} main.c 공조시스템 추가 (hvac)

- stm32_project/Core/Src/main.c
> [PR] modify main.c

- stm32_project/Core/Src/hvac.c
> [PR] modify hvac.c main.c

- stm32_project/.cproject
- stm32_project/Core/Inc/STM_LCD16X2.h
- stm32_project/Core/Src/STM_LCD16X2.c
- stm32_project/Core/Src/main.c
LCD 103보드에서 활성화 완료
초기값, 충전로직 변경필요,
> [PR] LCD 활성화, 로직 변경 필요

- stm32_project/Core/Inc/hvac.h
- stm32_project/Core/Inc/main.h
- stm32_project/Core/Src/hvac.c
- stm32_project/Core/Src/main.c
> [PR] modify main, hvac

- .gitignore
- stm32_project/.settings/language.settings.xml
- stm32_project/Core/Inc/LCD_Logic.h
- stm32_project/Core/Inc/STM_LCD16X2.h
- stm32_project/Core/Src/LCD_Logic.c
- stm32_project/Core/Src/STM_LCD16X2.c
- stm32_project/Core/Src/main.c
> [PR] LCD.c warning 제거

- stm32_project/Core/Inc/LCD_Logic.h
- stm32_project/Core/Inc/LCD_def.h
- stm32_project/Core/Src/LCD_Logic.c
로직 추가
- 임의 모터 속도에 따라 차량 메인 배터리(에너지) 감소
- 창문, 선루프 작동, 히터 작동, 에어컨 작동, 오디오 작동 메시지에 따라 선루프 배터리 감소
- 선루프 닫혀있을 때 임의의 조도값에 비례하여 선루프 배터리 충전
> [PR] LCD로직 메시지에 맞게 수정

- stm32_project/Core/Src/main.c
LCD Actuator == 0 로직 추가
배터리 상태 2개 = 0
사용 배터리 = 0 
전원 = 0
LCD_ nodisplay()
> [PR] LCD Actuator == 0 로직 추가

- stm32_project/Core/Inc/OurCan_message.h
- stm32_project/Core/Inc/OurCan_signal.h
- stm32_project/Core/Inc/can.h
> [PR] CAN DB 업데이트

- stm32_project/Core/Src/main.c
> [PR] Task 위치 변경

- rpi_project/src/can_setup.sh
> [PR] Add files via upload can_setup.sh

- rpi_project/README.md
- rpi_project/src/can_setup.sh
> [PR] Dev rpi4

- tc275_project/Cpu0_Main.c
- tc275_project/inc/queue.h
[Cpu0_Main.c]
테스트 모드 추가, 오디오 로직 버그 수정
[queue.h]
오디오 음성 명령 추가
> [PR] TC275 내부 로직 업데이트

- stm32_project/Core/Inc/sunroof.h
- stm32_project/Core/Inc/window.h
- stm32_project/Core/Src/DFPlayer.c
- stm32_project/Core/Src/can.c
- stm32_project/Core/Src/main.c
> [PR] modify audio

- stm32_project/Core/Inc/LCD_Logic.h
- stm32_project/Core/Src/DFPlayer.c
- stm32_project/Core/Src/LCD_Logic.c
- stm32_project/Core/Src/main.c
차량 배터리가 30%미만이다.
- 예비 배터리 우선 사용
- 예비배터리가 0이되면 차량 배터리 사용
차량 배터리가 30%이상이다.
- 예비 배터리가 50%이상이다
- 예비배터리 우선사용
- 예비 배터리가 50%미만이다.
- 메인베터리를 우선으로 사용한다.
- 예비배터리가 충전중이라면 충전중인 배터리도 함께 사용한다.  
차량 배터리가 모두 사용되면, 시동을 종료한다
시나리오 반영
> [PR] 배터리 로직 수정 및 배터리 오링시 사운드 출력

- stm32_project/Core/Inc/Common_def.h
- stm32_project/Core/Inc/LCD_Logic.h
- stm32_project/Core/Src/LCD_Logic.c
- stm32_project/Core/Src/main.c
LCD Utility 로직 추가 
driving 모드일때만 모터동작하도록
> [PR] LCD Utility 로직 추가

- stm32_project/Core/Src/LCD_Logic.c
- stm32_project/Core/Src/STM_LCD16X2.c
- stm32_project/Core/Src/sunroof.c
- stm32_project/Core/Src/window.c
LCD안쓰는 코드 주석, 창문, 썬루프 제어로직 수정
배터리로직 추가수정
> [PR] LCD안쓰는 코드 주석, 창문, 썬루프 제어로직 수정

- tc275_project/Cpu0_Main.c
tc275 내부 로직 최종 수정, queue.h 오디오 파일 매핑, 오디오 시간 로직 추가
> [PR] TC275 내부 로직 최종 업로드

- stm32_project/Core/Inc/window.h
- stm32_project/Core/Src/LCD_Logic.c
- stm32_project/Core/Src/main.c
- stm32_project/Core/Src/window.c
창문 로직 제어 
실제 값에 맞게 창문, 선루프 PWM 조정 필요
> [PR] 창문 로직 제어

- stm32_project/Core/Inc/sunroof.h
- stm32_project/Core/Inc/window.h
- stm32_project/Core/Src/gpio.c
- stm32_project/Core/Src/main.c
- stm32_project/Core/Src/sunroof.c
- stm32_project/Core/Src/tim.c
- stm32_project/Core/Src/window.c
창문 PWM은 괜찮고, 데모 전 선루프 PWM만 좀 바꾸면 괜찮을듯
> [PR] final 수정

- Cpu0_Main.c
> TC275 메인 로직 변경
